### ISSUE TITLE
Empty request body

### ISSUE THREAD

**Issue by mregiste** [Olanetsoft/jwt-project#2]
Configured and setup database, added .env for the all the right settings
Download the zip, npm install, npm start and used postman to send the post and req.body is empty

**Comment by juninhokaponne** [comment]
Are you connected to mongodb correctly ?

**Comment by mregiste** [comment]
Yes, I have tested that independently. The body of the request contains on entries and it won’t make it to this part of the code if the DB were not setup properly.

**Comment by juninhokaponne** [comment]
Because I tested all endpoints and req.body is not coming up empty!

I just cloned , npm start and npm dev run and it worked correctly, then I debugged the req.body return and it is returning what the user passes in the body.

**Comment by juninhokaponne** [comment]
Share your code to make it easier to help you

**Comment by mregiste** [comment]
Thank you for your time but there must be an env difference. If it works for you don't bother with my setup, I've implemented something else that works for me.
